### ISSUE TITLE
online demo would be great

### ISSUE THREAD

**Issue by luckylooke** [dannyradden/single-character-input-boxes#4]
For quick test whether results satisfy my needs, the online demo would be the best! 
Thanks! 
:)

**Comment by luckylooke** [comment]
So I have cloned repo, downloaded half of the internet with 'npm i' :D and tested demo locally and this is what I have found so far:
* missing feature of pasting whole code at once (you can use [onPaste](https://developer.mozilla.org/en-US/docs/Web/API/Element/paste_event))
** ideally with selected any of inputs
* I am not able to edit input, when I lose selection in input. So it would be better to be able to edit input without the selection, because there are plenty of options how to lose that selection, like clicking twice into input for example or going to side with cursor keys.
* on android device when I am removing last input character I have to tap "delete key" twice to remove it... then every other is OK
* on iphone every character the keyboard type changes from numeric to letters (can be fixed by setting inputs to type=number, but then maxLength is ignored what needs to be handled, for example by onKeyPress="if(this.value.length===1) return false;"
* on IE11/Win10 demo does not work at all as it fails on `Object doesn't support property or method 'fill'` can be fixed by polyfilling or rewrite to older js

Nice work! 👏 

Thank you for sharing 🙂

**Comment by dannyradden** [comment]
Thanks for the feedback! I will update the repo with some fixes when I get a chance.

**Comment by dannyradden** [comment]
Demo has been added 🎉🎉 🎉

**Comment by luckylooke** [comment]
great :clap: 
I have tried to paste whole code but it catches only first character into first box, others are ignored :/

**Comment by dannyradden** [comment]
Aw yes, implementing the paste functionality is next on my list. Ill try to get to it this weekend.

**Comment by luckylooke** [comment]
You don't need to hurry, I am not using your lib, I was looking for inspiration when I was solving same kind of inputs in our Vue project. Only thing my implementation is missing right now is autofill two-factor code by 1password. So don't forget to put "password mnagers" item into your list 😉

**Comment by dannyradden** [comment]
Hmm, any idea how I would get it to play nicely with pw managers?

**Comment by luckylooke** [comment]
1password have problem with splitted inputs, therefore it does not work automatically... but I want to try hidden input for password managers.. but didnt tried yet, as it has low priority I dont know when I try it. What I know so far, there is no easy way how to detect password managers by js.
