### ISSUE TITLE
Feature request - input props

### ISSUE THREAD

**Issue by linusnorton** [dannyradden/single-character-input-boxes#7]
Thank you for creating this component. 

It would be useful in my case if I was able to pass through properties to the input boxes. Specifically I am looking to set a placeholder and some custom styling.

I would expect something like:

```
        <RICIBs
          amount={3}
          handleOutputString={this.handleOutput}
          inputProps={ [
            { placeholder: "_", className: "color-red" },
            { placeholder: "_", styles: { "color": "blue" } },
            { placeholder: "_", styles: { "color": "green" } }
        ]}/>
```

**Comment by dannyradden** [comment]
That's a great idea! I'll work on implementing it.

**Comment by linusnorton** [comment]
I actually did something quick and dirty 

https://github.com/linusnorton/single-character-input-boxes/commit/c969dc26c38dd16a89d0efdaafddc09f2115523c

**Comment by dannyradden** [comment]
Nice, is it working as intended?

**Comment by linusnorton** [comment]
Yes, but I did very little testing so it might break with certain values

**Comment by juliandierker** [comment]
Is this feature already in the npm package?

**Comment by dannyradden** [comment]
Aw yeah, I have it updated here mine too, Ill push it up shortly.

**Comment by dannyradden** [comment]
Feature pushed in release 1.1.0! 🎉

**Comment by dannyradden** [comment]
Feature pushed in release 1.1.0! 🎉
